(clear)
(load "sudoku.clp")
(load "solve.clp")
(load "guess.clp")
(load "output-frills.clp")
(load "test//test-naked-single-diagonal.clp")
(open "test.txt" output "w")
(reset)
(assert (try guessing))
