(clear)
(load "sudoku.clp")
(load "solve.clp")
(load "output-frills.clp")
(load "test//test-naked-single-diagonal.clp")
(open "test.txt" output "w")
(reset)
(run)
(close output)
(clear)
(load "sudoku.clp")
(load "solve.clp")
(load "output-frills.clp")
(load "test//test-hidden-single-diagonal.clp")
(open "test.txt" output "w")
(reset)
(run)
(close output)
(clear)
(load "sudoku.clp")
(load "solve.clp")
(load "output-frills.clp")
(load "test//test-locked-candidate-single-line-diagonal.clp")
(open "test.txt" output "w")
(reset)
(assert (stress-test))
(run)
(close output)
